# TBEP R Training

[R](https://www.r-project.org/) is a language for statistical computing as well as a general purpose programming language. R has become one of the primary languages used in data science and for data analysis across many of the natural sciences. This training workshop will provide attendees with the foundations for continued learning of R and for analysis of a range of data types. 

__Please RSVP using the link [here](https://forms.gle/43XsiT5JdPfk59iW7)__.

## Course objectives

This course is designed to expose you to the fundamentals of using R for reproducible data analysis workflows.  You will not be experts by the end of the course, but you will have a solid foundation for continued learning.  By the end of this course you will be able to or have the resources to find out how to:

* Use R to import and organize data
* Create plots using R packages for exploratory data analysis
* Create maps in R to explore spatial patterns

## Agenda

* __9:00 - 10:00__ The what, why, and how of R
  
  BREAK
  
* __10:15-12:00__ Data wrangling and plotting

  LUNCH
  
* __1:00 - 2:30__ Using the tbeptools package

  BREAK
  
* __2:45 - 4:00__ Spatial data analysis in R

## Software requirements

All required software will be pre-installed on computers provided by the training venue.  You are not required to bring your own laptop.  If you prefer to bring your own laptop, please have a current version of RStudio and R installed. The [setup instructions](setup.html) will guide you through the installation the process.  Take note of the required R packages that you must also download and install.  Please contact the instructor with any questions or issues related to setup.  

## Instructor

[Marcus Beck](https://fawda123.github.io/CV/Beck_CV.pdf) ([mbeck@tbep.org](mailto:mbeck@tbep.org)) - Marcus is the Program Scientist for the Tampa Bay Estuary Program and is developing data analysis and visualization methods for Bay health indicators.  He received his BS in Zoology from the University of Florida in 2007 and his MSc and PhD in Conservation Biology from the University of Minnesota in 2009 and 2013. Marcus has experience researching environmental indicators and developing open science products to support environmental decision-making.  He has over ten years of experience using and developing software in the R Statistical Programming Language and is the lead developer for the SWMPr R package to retrieve, organize, and analyze NERRS data from the SWMP network.

## Source content

All source materials for this website can be accessed at https://github.com/tbep-tech/tbep-r-training
