---
title: "A soft introduction to Shiny"
output: 
  html_document:
    toc: true
    toc_float: 
       collapsed: true
self_contained: yes
css: styles.css
---

```{r setup, message = F, warning = F, results = 'hide', echo = F}
knitr::opts_chunk$set(echo = T, warning = F, message = F, fig.path = 'figure/')
```

Full disclaimer: Much of this content was pillaged from the [Mastering Shiny](https://mastering-shiny.org/index.html) text.  Please consult that text for a much more informed description of how to build shiny apps!

## Outline

* [What is and Why Shiny?]
* [New concepts]
* [Resources]

## What is and why Shiny? 

Shiny is an R package that lets you create rich, interactive web applications.  Shiny lets you take an existing R script and expose it using a web browser so that you or anybody else can use it outside of R.  Shiny is commonly used to: 

* Communicate complex workflows to a non-technical audience with informative visualizations and interactive components
* Share your analysis easily with colleagues without having to walk them through details of your script
* Help inform your understanding of an analysis by creating a user interface to quickly evaluate 

In the applied sciences world, Shiny can be a very important tool to "bridge the research-management divide"!  A very simple example is the use of Shiny to replace a 500 page document with hundreds of figures with a simple application that allows the user to jump to an exact slide of the data that they want.   

There are many advantages to using Shiny over other platforms for creating web applications.  As R users, the beauty of Shiny is that you only need to know how to use R.  You do not need to know anything about web programming, such as HTML, CSS, or JavaScript.  On the other hand, Shiny gives you the power to tap into the broader suite of web programming tools when you're ready to or have a need to expand your application. 

More simply, Shiny lets you create a web interface for any R workflow. This means that whatever custom analysis or graphic you've made can be fully integrated into your dashboard, unlike other platforms that may have rigid and less customizable templates designed for ease of use.  

## New concepts

Shiny can be challenging at first because it introduces a new way of thinking about your code. "Simple" R scripts are designed to run linearly, being read from top to bottom.  You write your script, source the code to your console, and get some results or objects created after running the script. 

A shiny app runs from an R script, but instead of executing code linearly, it uses *reactive* programming that detects when an input is changed on the application, runs the minimal amount of code that uses that input, then updates the output as needed.  So, rather than thinking of the script as linear, think of it as having interconnected components that share pieces of information to produce the results.  This can be daunting at first because it requires you think about which pieces of your code require inputs from other pieces and how that information is used to create output.  

User interface: inputs, outputs
server: processing

## Using RMarkdown for shiny apps

## A motivating example

Last year we talked about using R to [write your own functions](https://tbep-tech.github.io/tbep-r-training/functions.html).  We started with a simple example of filtering and plotting data from the FWC [Fisheries Independent Monitoring](https://geodata.myfwc.com/datasets/68fb6774b58a40a08a6f87959aaa53c4_26/data) dataset.  

## Debugging R Shiny apps

Use the browser() but DO NOT run from the knit option. 

## Sharing your applications

## Resources

* [Mastering Shiny](https://mastering-shiny.org/index.html): By Hadley Wickham, to be published June 2021
* [RStudio Shiny cheatsheet](https://github.com/rstudio/cheatsheets/raw/master/shiny.pdf)
